
-- Create table for photographer applications
CREATE TABLE IF NOT EXISTS public.photographer_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact TEXT NOT NULL,
  description TEXT,
  portfolio_urls TEXT[], -- Array of URLs
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.photographer_applications ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (for applications)
CREATE POLICY "Allow public inserts for applications" 
ON public.photographer_applications 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow service role to do everything (implicit, but good to know)
-- No SELECT policy for anon means public cannot read the list (secure)
